'use client';

import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Edit3, AlertTriangle, TrendingUp, Info, Clock } from 'lucide-react';
import { Insight, KPIData, HealthStatus } from '@/types/business';
import { getKPIDefinition } from '@/lib/business-logic/kpi-definitions';

interface InsightCardProps {
  insight: Insight;
  kpiData: KPIData;
  onEdit?: (insight: Insight) => void;
  compact?: boolean;
}

const InsightCard: React.FC<InsightCardProps> = ({ 
  insight, 
  kpiData, 
  onEdit,
  compact = false 
}) => {
  const [isEditing, setIsEditing] = useState(false);
  const definition = getKPIDefinition(insight.kpiId);

  const getPriorityColor = (priority: string): string => {
    switch (priority) {
      case 'high': return 'border-red-200 bg-red-50';
      case 'medium': return 'border-yellow-200 bg-yellow-50';
      case 'low': return 'border-blue-200 bg-blue-50';
      default: return 'border-gray-200 bg-gray-50';
    }
  };

  const getPriorityIcon = (priority: string) => {
    switch (priority) {
      case 'high': return <AlertTriangle className="w-4 h-4 text-red-500" />;
      case 'medium': return <TrendingUp className="w-4 h-4 text-yellow-500" />;
      case 'low': return <Info className="w-4 h-4 text-blue-500" />;
      default: return <Info className="w-4 h-4 text-gray-500" />;
    }
  };

  const getHealthColor = (status: HealthStatus): string => {
    switch (status) {
      case 'excellent': return 'text-green-600 bg-green-100';
      case 'good': return 'text-blue-600 bg-blue-100';
      case 'warning': return 'text-yellow-600 bg-yellow-100';
      case 'critical': return 'text-red-600 bg-red-100';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  const handleEdit = () => {
    setIsEditing(true);
    onEdit?.(insight);
  };

  const formatDate = (dateString: string): string => {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  if (compact) {
    return (
      <motion.div
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.3 }}
        className={`p-4 rounded-lg border ${getPriorityColor(insight.priority)} hover:shadow-md transition-shadow cursor-pointer`}
        onClick={() => onEdit?.(insight)}
      >
        <div className="flex items-start gap-3">
          {getPriorityIcon(insight.priority)}
          <div className="flex-1 min-w-0">
            <h4 className="font-medium text-gray-900 text-sm mb-1 truncate">
              {insight.title}
            </h4>
            <p className="text-xs text-gray-600 line-clamp-2">
              {insight.observation}
            </p>
            <div className="flex items-center gap-2 mt-2">
              <span className={`text-xs px-2 py-1 rounded-full ${getHealthColor(kpiData.healthStatus)}`}>
                {definition.name}
              </span>
              <span className="text-xs text-gray-400">
                {formatDate(insight.generatedAt)}
              </span>
            </div>
          </div>
        </div>
      </motion.div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className={`bg-white rounded-lg shadow-sm border-2 ${getPriorityColor(insight.priority)} overflow-hidden`}
    >
      {/* Header */}
      <div className="p-6 pb-4">
        <div className="flex items-start justify-between mb-4">
          <div className="flex items-center gap-3">
            {getPriorityIcon(insight.priority)}
            <div>
              <h3 className="text-lg font-semibold text-gray-900">
                {insight.title}
              </h3>
              <div className="flex items-center gap-2 mt-1">
                <span className={`text-xs px-2 py-1 rounded-full ${getHealthColor(kpiData.healthStatus)}`}>
                  {definition.name}
                </span>
                <span className="text-xs text-gray-400">
                  Priority: {insight.priority}
                </span>
                {insight.isAutoGenerated && (
                  <span className="text-xs text-gray-400 flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    Auto-generated
                  </span>
                )}
              </div>
            </div>
          </div>
          
          {onEdit && (
            <button
              onClick={handleEdit}
              className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
              title="Edit insight"
            >
              <Edit3 className="w-4 h-4 text-gray-400" />
            </button>
          )}
        </div>

        <div className="text-xs text-gray-400 mb-4">
          Generated: {formatDate(insight.generatedAt)}
        </div>
      </div>

      {/* What → So What → Now What Framework */}
      <div className="px-6 pb-6 space-y-4">
        {/* What: Observation */}
        <div className="bg-gray-50 p-4 rounded-lg">
          <div className="flex items-center gap-2 mb-2">
            <div className="w-6 h-6 bg-blue-500 text-white rounded-full flex items-center justify-center text-xs font-bold">
              1
            </div>
            <h4 className="font-semibold text-gray-900 text-sm">What</h4>
            <span className="text-xs text-gray-500">(Observation)</span>
          </div>
          <p className="text-sm text-gray-700 leading-relaxed pl-8">
            {insight.observation}
          </p>
        </div>

        {/* So What: Business Impact */}
        <div className="bg-yellow-50 p-4 rounded-lg">
          <div className="flex items-center gap-2 mb-2">
            <div className="w-6 h-6 bg-yellow-500 text-white rounded-full flex items-center justify-center text-xs font-bold">
              2
            </div>
            <h4 className="font-semibold text-gray-900 text-sm">So What</h4>
            <span className="text-xs text-gray-500">(Business Impact)</span>
          </div>
          <p className="text-sm text-gray-700 leading-relaxed pl-8">
            {insight.businessImpact}
          </p>
        </div>

        {/* Now What: Action */}
        <div className="bg-green-50 p-4 rounded-lg">
          <div className="flex items-center gap-2 mb-2">
            <div className="w-6 h-6 bg-green-500 text-white rounded-full flex items-center justify-center text-xs font-bold">
              3
            </div>
            <h4 className="font-semibold text-gray-900 text-sm">Now What</h4>
            <span className="text-xs text-gray-500">(Action)</span>
          </div>
          <p className="text-sm text-gray-700 leading-relaxed pl-8">
            {insight.action}
          </p>
        </div>
      </div>

      {/* KPI Context */}
      <div className="px-6 pb-6 pt-4 border-t border-gray-100">
        <div className="flex items-center justify-between text-sm">
          <div className="flex items-center gap-4">
            <span className="text-gray-500">KPI Context:</span>
            <span className="font-medium text-gray-900">{definition.name}</span>
            <span className={`px-2 py-1 rounded-full text-xs ${getHealthColor(kpiData.healthStatus)}`}>
              {kpiData.healthStatus}
            </span>
          </div>
          <div className="text-gray-500">
            Current: {kpiData.currentValue} {definition.unit}
          </div>
        </div>
      </div>
    </motion.div>
  );
};

export default InsightCard;
