// Business Intelligence & Executive Dashboard Types
// Designed for C-level decision makers with clear business terminology

export type KPIId = 
  | 'revenue' 
  | 'revenue-growth' 
  | 'profit-margin' 
  | 'expense-ratio' 
  | 'customer-health'
  | 'churn-rate'
  | 'clv';

export type HealthStatus = 'excellent' | 'good' | 'warning' | 'critical';

export type TrendDirection = 'up' | 'down' | 'stable';

export interface KPIDefinition {
  id: KPIId;
  name: string;
  description: string;
  businessMeaning: string;
  whyItMatters: string;
  goodValueIndicator: string;
  badValueIndicator: string;
  unit: string;
  category: 'financial' | 'operational' | 'customer';
}

export interface KPIData {
  id: KPIId;
  currentValue: number;
  previousValue: number;
  targetValue: number;
  trend: TrendDirection;
  healthStatus: HealthStatus;
  lastUpdated: string;
  historicalValues: {
    period: string;
    value: number;
  }[];
}

export interface Insight {
  id: string;
  kpiId: KPIId;
  title: string;
  observation: string; // What: factual metric behavior
  businessImpact: string; // So What: why leadership should care
  action: string; // Now What: decision or follow-up
  priority: 'high' | 'medium' | 'low';
  generatedAt: string;
  isAutoGenerated: boolean;
}

export interface RiskIndicator {
  id: string;
  kpiId: KPIId;
  status: HealthStatus;
  title: string;
  explanation: string;
  thresholdLogic: string;
  consecutivePeriods: number;
  severity: 'high' | 'medium' | 'low';
}

export interface Recommendation {
  id: string;
  insightId: string;
  kpiId: KPIId;
  title: string;
  description: string;
  actionType: 'increase' | 'reduce' | 'investigate' | 'prioritize' | 'maintain';
  expectedImpact: string;
  timeframe: 'immediate' | 'short-term' | 'long-term';
  effort: 'low' | 'medium' | 'high';
  confidence: 'high' | 'medium' | 'low';
}

export interface ExecutiveSummary {
  id: string;
  period: string;
  overallHealth: HealthStatus;
  keyHighlights: string[];
  topRisks: {
    title: string;
    description: string;
    kpiId: KPIId;
  }[];
  topOpportunities: {
    title: string;
    description: string;
    kpiId: KPIId;
  }[];
  narrative: string;
  generatedAt: string;
}

export interface BusinessHealthScore {
  overall: number;
  financial: number;
  operational: number;
  customer: number;
  status: HealthStatus;
  factors: {
    category: string;
    score: number;
    weight: number;
  }[];
}

export interface DashboardData {
  kpis: KPIData[];
  insights: Insight[];
  risks: RiskIndicator[];
  recommendations: Recommendation[];
  executiveSummary: ExecutiveSummary;
  businessHealthScore: BusinessHealthScore;
  lastUpdated: string;
}

// API Response Types
export interface APIResponse<T> {
  data: T;
  success: boolean;
  message?: string;
  timestamp: string;
}

export type KPIDataResponse = APIResponse<KPIData[]>;
export type InsightsResponse = APIResponse<Insight[]>;
export type RecommendationsResponse = APIResponse<Recommendation[]>;
export type ExecutiveSummaryResponse = APIResponse<ExecutiveSummary>;

// Component Props Types
export interface KPICardProps {
  kpi: KPIData;
  definition: KPIDefinition;
  showDetails?: boolean;
  onClick?: () => void;
}

export interface InsightCardProps {
  insight: Insight;
  kpiData: KPIData;
  onEdit?: (insight: Insight) => void;
  compact?: boolean;
}

export interface RiskIndicatorProps {
  risk: RiskIndicator;
  kpiData: KPIData;
  showDetails?: boolean;
}

export interface RecommendationCardProps {
  recommendation: Recommendation;
  insight: Insight;
  onAction?: (recommendation: Recommendation) => void;
}

// Business Logic Types
export interface ThresholdRule {
  kpiId: KPIId;
  excellent: { min?: number; max?: number };
  good: { min?: number; max?: number };
  warning: { min?: number; max?: number };
  critical: { min?: number; max?: number };
}

export interface InsightRule {
  id: string;
  name: string;
  kpiId: KPIId;
  condition: (data: KPIData) => boolean;
  generateInsight: (data: KPIData) => Omit<Insight, 'id' | 'generatedAt' | 'isAutoGenerated'>;
  priority: 'high' | 'medium' | 'low';
}
